import "server-only";

import type { Metadata } from "next";

// import { siteConfig } from "@/shared/config.ts";
import { languages } from "@/shared/i18n/languages.ts";

import { ThemeProvider } from "./theme-provider.tsx";
import { FontProvider } from "./font-provider.tsx";
import { Analytics } from "./analytics.tsx";

import "../shared/globals.css";

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    // lang: Language;
  };
}

const DEFAULT_LANG = languages[0] ?? { code: "tr", dir: "ltr" };

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = async (props: RootLayoutProps) => {
  return (
    <html
      lang={DEFAULT_LANG.code}
      dir={DEFAULT_LANG.dir}
      suppressHydrationWarning={true}
    >
      <head />
      <body>
        <FontProvider />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
        >
          {props.children}
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
};

export { metadata, Layout, Layout as default };
